name: Deploy to Netlify

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Update to use v3 for Node.js v20 support
      with:
        node-version: '20'  # Use Node.js v20

    - name: Install pnpm
      run: npm install -g pnpm  # Install pnpm globally

    - name: Install dependencies with pnpm
      run: pnpm install  # Use pnpm to install dependencies

    - name: Install Netlify CLI locally
      run: pnpm add netlify-cli  # Install Netlify CLI as a local dependency

    - name: Build the app
      run: pnpm run build  # Replace this with your specific build command if necessary

    - name: Deploy to Netlify
      run: npx netlify deploy --prod --dir=./build  # Use npx to run locally installed Netlify CLI
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
