name: Deploy to Netlify

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version (change this if necessary)

    - name: Install dependencies
      run: npm install  # Runs npm install to install your project dependencies

    - name: Install Netlify CLI
      run: npm install -g netlify-cli  # Installs the Netlify CLI

    - name: Build the app
      run: npm run build  # Replace this with your specific build command if necessary

    - name: Deploy to Netlify
      run: netlify deploy --prod --dir=./build  # Specify the correct directory for build output
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Uses the token for authentication
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  # Optionally use a secret for the site ID
